site_name: NL Baseball Docs
nav:
    - Index: index.md
    - Installation: installation.md
    - Data Scraper: datascraper.md
    - Dashboard: dashboard.md
    - Backlog: backlog.md
    - About: about.md
theme: readthedocs