https://statsapi.mlb.com/api/v1/people?personIds=465668,636072,642720,457453,666198,571851,642488,644433,605530,642282,669274,665947,650851,691829,649955,676875,645291,689168,687850,660745,622362,678882,682516,666635,661250,677642,678281,683666,683408,687677,680884,678427,672561,677804,680634,691828,681606,679968,683398,683393,682888,683430,682654,682651,678799,678751,645277,593428,544369,445276,595777,570731,592743,467008,665989,678486,&hydrate=stats(type=[season],season=2019,sportId=1)

{
  "copyright" : "Copyright 2020 MLB Advanced Media, L.P.  Use of any content on this page acknowledges agreement to the terms posted here http://gdx.mlb.com/components/copyright.txt",
  "people" : [ {
    "id" : 465668,
    "fullName" : "Roger Bernadina",
    "link" : "/api/v1/people/465668",
    "firstName" : "Rogearvin",
    "lastName" : "Bernadina",
    "primaryNumber" : "9",
    "birthDate" : "1984-06-12",
    "currentAge" : 35,
    "birthCity" : "Willemstad",
    "birthCountry" : "Curacao",
    "height" : "6' 2\"",
    "weight" : 210,
    "active" : true,
    "primaryPosition" : {
      "code" : "7",
      "name" : "Outfielder",
      "type" : "Outfielder",
      "abbreviation" : "LF"
    },
    "useName" : "Roger",
    "middleName" : "A.",
    "boxscoreName" : "Bernadina",
    "nickName" : "The Shark",
    "gender" : "M",
    "isPlayer" : true,
    "isVerified" : true,
    "mlbDebutDate" : "2008-06-29",
    "batSide" : {
      "code" : "L",
      "description" : "Left"
    },
    "pitchHand" : {
      "code" : "L",
      "description" : "Left"
    },
    "nameFirstLast" : "Roger Bernadina",
    "nameSlug" : "roger-bernadina-465668",
    "firstLastName" : "Roger Bernadina",
    "lastFirstName" : "Bernadina, Roger",
    "lastInitName" : "Bernadina, R",
    "initLastName" : "R Bernadina",
    "fullFMLName" : "Rogearvin A. Bernadina",
    "fullLFMName" : "Bernadina, Rogearvin A.",
    "strikeZoneTop" : 3.28,
    "strikeZoneBottom" : 1.45
  }, {
    "id" : 636072,
    "fullName" : "Calten Daal",
    "link" : "/api/v1/people/636072",
    "firstName" : "Carlton",
    "lastName" : "Daal",
    "primaryNumber" : "44",
    "birthDate" : "1993-08-01",
    "currentAge" : 26,
    "birthCity" : "Willemstad",
    "birthCountry" : "Curacao",
    "height" : "6' 1\"",
    "weight" : 180,
    "active" : true,
    "primaryPosition" : {
      "code" : "6",
      "name" : "Shortstop",
      "type" : "Infielder",
      "abbreviation" : "SS"
    },
    "useName" : "Calten",
    "middleName" : "Arron",
    "boxscoreName" : "Daal",
    "gender" : "M",
    "isPlayer" : true,
    "isVerified" : true,
    "batSide" : {
      "code" : "R",
      "description" : "Right"
    },
    "pitchHand" : {
      "code" : "R",
      "description" : "Right"
    },
    "nameFirstLast" : "Calten Daal",
    "nameSlug" : "calten-daal-636072",
    "firstLastName" : "Calten Daal",
    "lastFirstName" : "Daal, Calten",
    "lastInitName" : "Daal, C",
    "initLastName" : "C Daal",
    "fullFMLName" : "Carlton Arron Daal",
    "fullLFMName" : "Daal, Carlton Arron",
    "strikeZoneTop" : 3.61,
    "strikeZoneBottom" : 1.62
  }, {
    "id" : 642720,
    "fullName" : "Ray-Patrick Didder",
    "link" : "/api/v1/people/642720",
    "firstName" : "Ray-Patrick",
    "lastName" : "Didder",
    "birthDate" : "1994-10-01",
    "currentAge" : 25,
    "birthCity" : "Oranjestad",
    "birthCountry" : "Aruba",
    "height" : "6' 0\"",
    "weight" : 170,
    "active" : true,
    "primaryPosition" : {
      "code" : "O",
      "name" : "Outfield",
      "type" : "Outfielder",
      "abbreviation" : "OF"
    },
    "useName" : "Ray-Patrick",
    "middleName" : "Elijah Khalil",
    "boxscoreName" : "Didder",
    "gender" : "M",
    "isPlayer" : true,
    "isVerified" : true,
    "batSide" : {
      "code" : "R",
      "description" : "Right"
    },
    "pitchHand" : {
      "code" : "R",
      "description" : "Right"
    },
    "nameFirstLast" : "Ray-Patrick Didder",
    "nameSlug" : "ray-patrick-didder-642720",
    "firstLastName" : "Ray-Patrick Didder",
    "lastFirstName" : "Didder, Ray-Patrick",
    "lastInitName" : "Didder, R",
    "initLastName" : "R Didder",
    "fullFMLName" : "Ray-Patrick Elijah Khalil Didder",
    "fullLFMName" : "Didder, Ray-Patrick Elijah Khalil",
    "strikeZoneTop" : 3.371,
    "strikeZoneBottom" : 1.535
  }, {
    "id" : 457453,
    "fullName" : "Jair Jurrjens",
    "link" : "/api/v1/people/457453",
    "firstName" : "Jair",
    "lastName" : "Jurrjens",
    "primaryNumber" : "49",
    "birthDate" : "1986-01-29",
    "currentAge" : 34,
    "birthCity" : "Santa Maria",
    "birthCountry" : "Curacao",
    "height" : "6' 1\"",
    "weight" : 200,
    "active" : true,
    "primaryPosition" : {
      "code" : "1",
      "name" : "Pitcher",
      "type" : "Pitcher",
      "abbreviation" : "P"
    },
    "useName" : "Jair",
    "middleName" : "Francoise",
    "boxscoreName" : "Jurrjens",
    "gender" : "M",
    "isPlayer" : true,
    "isVerified" : true,
    "mlbDebutDate" : "2007-08-15",
    "batSide" : {
      "code" : "R",
      "description" : "Right"
    },
    "pitchHand" : {
      "code" : "R",
      "description" : "Right"
    },
    "nameFirstLast" : "Jair Jurrjens",
    "nameSlug" : "jair-jurrjens-457453",
    "firstLastName" : "Jair Jurrjens",
    "lastFirstName" : "Jurrjens, Jair",
    "lastInitName" : "Jurrjens, J",
    "initLastName" : "J Jurrjens",
    "fullFMLName" : "Jair Francoise Jurrjens",
    "fullLFMName" : "Jurrjens, Jair Francoise",
    "strikeZoneTop" : 3.38,
    "strikeZoneBottom" : 1.5
  }, {
    "id" : 666198,
    "fullName" : "Carter Kieboom",
    "link" : "/api/v1/people/666198",
    "firstName" : "Carter",
    "lastName" : "Kieboom",
    "primaryNumber" : "8",
    "birthDate" : "1997-09-03",
    "currentAge" : 22,
    "birthCity" : "Marietta",
    "birthStateProvince" : "GA",
    "birthCountry" : "USA",
    "height" : "6' 2\"",
    "weight" : 190,
    "active" : true,
    "primaryPosition" : {
      "code" : "6",
      "name" : "Shortstop",
      "type" : "Infielder",
      "abbreviation" : "SS"
    },
    "useName" : "Carter",
    "middleName" : "Alswinn",
    "boxscoreName" : "Kieboom, C",
    "gender" : "M",
    "isPlayer" : true,
    "isVerified" : false,
    "draftYear" : 2016,
    "stats" : [ {
      "type" : {
        "displayName" : "season"
      },
      "group" : {
        "displayName" : "hitting"
      },
      "exemptions" : [ ],
      "splits" : [ {
        "season" : "2019",
        "stat" : {
          "gamesPlayed" : 11,
          "groundOuts" : 10,
          "airOuts" : 8,
          "runs" : 4,
          "doubles" : 0,
          "triples" : 0,
          "homeRuns" : 2,
          "strikeOuts" : 16,
          "baseOnBalls" : 4,
          "intentionalWalks" : 1,
          "hits" : 5,
          "hitByPitch" : 0,
          "avg" : ".128",
          "atBats" : 39,
          "obp" : ".209",
          "slg" : ".282",
          "ops" : ".491",
          "caughtStealing" : 0,
          "stolenBases" : 0,
          "stolenBasePercentage" : ".---",
          "groundIntoDoublePlay" : 0,
          "numberOfPitches" : 168,
          "plateAppearances" : 43,
          "totalBases" : 11,
          "rbi" : 2,
          "leftOnBase" : 21,
          "sacBunts" : 0,
          "sacFlies" : 0,
          "babip" : ".143",
          "groundOutsToAirouts" : "1.25",
          "atBatsPerHomeRun" : "19.50"
        },
        "team" : {
          "id" : 120,
          "name" : "Washington Nationals",
          "link" : "/api/v1/teams/120"
        },
        "league" : {
          "id" : 104,
          "name" : "National League",
          "link" : "/api/v1/league/104"
        },
        "gameType" : "R"
      } ]
    } ],
    "mlbDebutDate" : "2019-04-26",
    "batSide" : {
      "code" : "R",
      "description" : "Right"
    },
    "pitchHand" : {
      "code" : "R",
      "description" : "Right"
    },
    "nameFirstLast" : "Carter Kieboom",
    "nameSlug" : "carter-kieboom-666198",
    "firstLastName" : "Carter Kieboom",
    "lastFirstName" : "Kieboom, Carter",
    "lastInitName" : "Kieboom, C",
    "initLastName" : "C Kieboom",
    "fullFMLName" : "Carter Alswinn Kieboom",
    "fullLFMName" : "Kieboom, Carter Alswinn",
    "strikeZoneTop" : 3.467,
    "strikeZoneBottom" : 1.589
  }, {
    "id" : 571851,
    "fullName" : "Spencer Kieboom",
    "link" : "/api/v1/people/571851",
    "firstName" : "Spencer",
    "lastName" : "Kieboom",
    "primaryNumber" : "27",
    "birthDate" : "1991-03-16",
    "currentAge" : 29,
    "birthCity" : "Mount Pleasant",
    "birthStateProvince" : "SC",
    "birthCountry" : "USA",
    "height" : "6' 0\"",
    "weight" : 210,
    "active" : true,
    "primaryPosition" : {
      "code" : "2",
      "name" : "Catcher",
      "type" : "Catcher",
      "abbreviation" : "C"
    },
    "useName" : "Spencer",
    "middleName" : "John",
    "boxscoreName" : "Kieboom, S",
    "nickName" : "Boomer",
    "gender" : "M",
    "isPlayer" : true,
    "isVerified" : true,
    "draftYear" : 2012,
    "pronunciation" : "KEE-boom",
    "mlbDebutDate" : "2016-10-02",
    "batSide" : {
      "code" : "R",
      "description" : "Right"
    },
    "pitchHand" : {
      "code" : "R",
      "description" : "Right"
    },
    "nameFirstLast" : "Spencer Kieboom",
    "nameSlug" : "spencer-kieboom-571851",
    "firstLastName" : "Spencer Kieboom",
    "lastFirstName" : "Kieboom, Spencer",
    "lastInitName" : "Kieboom, S",
    "initLastName" : "S Kieboom",
    "fullFMLName" : "Spencer John Kieboom",
    "fullLFMName" : "Kieboom, Spencer John",
    "strikeZoneTop" : 3.371,
    "strikeZoneBottom" : 1.535
  }, {
    "id" : 642488,
    "fullName" : "Ademar Rifaela",
    "link" : "/api/v1/people/642488",
    "firstName" : "Ademar",
    "lastName" : "Rifaela",
    "primaryNumber" : "91",
    "birthDate" : "1994-11-20",
    "currentAge" : 25,
    "birthCity" : "Willemstad",
    "birthCountry" : "Curacao",
    "height" : "5' 10\"",
    "weight" : 180,
    "active" : true,
    "primaryPosition" : {
      "code" : "7",
      "name" : "Outfielder",
      "type" : "Outfielder",
      "abbreviation" : "LF"
    },
    "useName" : "Ademar",
    "middleName" : "Bertty Aloysius",
    "boxscoreName" : "Rifaela",
    "gender" : "M",
    "isPlayer" : true,
    "isVerified" : true,
    "batSide" : {
      "code" : "L",
      "description" : "Left"
    },
    "pitchHand" : {
      "code" : "L",
      "description" : "Left"
    },
    "nameFirstLast" : "Ademar Rifaela",
    "nameSlug" : "ademar-rifaela-642488",
    "firstLastName" : "Ademar Rifaela",
    "lastFirstName" : "Rifaela, Ademar",
    "lastInitName" : "Rifaela, A",
    "initLastName" : "A Rifaela",
    "fullFMLName" : "Ademar Bertty Aloysius Rifaela",
    "fullLFMName" : "Rifaela, Ademar Bertty Aloysius",
    "strikeZoneTop" : 3.301,
    "strikeZoneBottom" : 1.504
  }, {
    "id" : 644433,
    "fullName" : "Chadwick Tromp",
    "link" : "/api/v1/people/644433",
    "firstName" : "Chadwick",
    "lastName" : "Tromp",
    "primaryNumber" : "82",
    "birthDate" : "1995-03-21",
    "currentAge" : 25,
    "birthCity" : "Oranjestad",
    "birthCountry" : "Aruba",
    "height" : "5' 9\"",
    "weight" : 205,
    "active" : true,
    "primaryPosition" : {
      "code" : "2",
      "name" : "Catcher",
      "type" : "Catcher",
      "abbreviation" : "C"
    },
    "useName" : "Chadwick",
    "middleName" : "Chandler",
    "boxscoreName" : "Tromp",
    "gender" : "M",
    "isPlayer" : true,
    "isVerified" : true,
    "batSide" : {
      "code" : "R",
      "description" : "Right"
    },
    "pitchHand" : {
      "code" : "R",
      "description" : "Right"
    },
    "nameFirstLast" : "Chadwick Tromp",
    "nameSlug" : "chadwick-tromp-644433",
    "firstLastName" : "Chadwick Tromp",
    "lastFirstName" : "Tromp, Chadwick",
    "lastInitName" : "Tromp, C",
    "initLastName" : "C Tromp",
    "fullFMLName" : "Chadwick Chandler Tromp",
    "fullLFMName" : "Tromp, Chadwick Chandler",
    "strikeZoneTop" : 3.285,
    "strikeZoneBottom" : 1.487
  }, {
    "id" : 605530,
    "fullName" : "Zander Wiel",
    "link" : "/api/v1/people/605530",
    "firstName" : "Alexander",
    "lastName" : "Wiel",
    "primaryNumber" : "89",
    "birthDate" : "1993-01-11",
    "currentAge" : 27,
    "birthCity" : "Murfreesboro",
    "birthStateProvince" : "TN",
    "birthCountry" : "USA",
    "height" : "6' 3\"",
    "weight" : 220,
    "active" : true,
    "primaryPosition" : {
      "code" : "3",
      "name" : "First Base",
      "type" : "Infielder",
      "abbreviation" : "1B"
    },
    "useName" : "Zander",
    "middleName" : "McBrayer",
    "boxscoreName" : "Wiel",
    "gender" : "M",
    "isPlayer" : true,
    "isVerified" : false,
    "draftYear" : 2015,
    "batSide" : {
      "code" : "R",
      "description" : "Right"
    },
    "pitchHand" : {
      "code" : "R",
      "description" : "Right"
    },
    "nameFirstLast" : "Zander Wiel",
    "nameSlug" : "zander-wiel-605530",
    "firstLastName" : "Zander Wiel",
    "lastFirstName" : "Wiel, Zander",
    "lastInitName" : "Wiel, Z",
    "initLastName" : "Z Wiel",
    "fullFMLName" : "Alexander McBrayer Wiel",
    "fullLFMName" : "Wiel, Alexander McBrayer",
    "strikeZoneTop" : 3.49,
    "strikeZoneBottom" : 1.601
  }, {
    "id" : 642282,
    "fullName" : "Juremi Profar",
    "link" : "/api/v1/people/642282",
    "firstName" : "Juremi",
    "lastName" : "Profar",
    "birthDate" : "1996-01-30",
    "currentAge" : 24,
    "birthCity" : "Willemstad",
    "birthCountry" : "Curacao",
    "height" : "6' 1\"",
    "weight" : 185,
    "active" : true,
    "primaryPosition" : {
      "code" : "5",
      "name" : "Third Base",
      "type" : "Infielder",
      "abbreviation" : "3B"
    },
    "useName" : "Juremi",
    "middleName" : "Gregorius",
    "boxscoreName" : "Profar",
    "gender" : "M",
    "isPlayer" : true,
    "isVerified" : true,
    "batSide" : {
      "code" : "R",
      "description" : "Right"
    },
    "pitchHand" : {
      "code" : "R",
      "description" : "Right"
    },
    "nameFirstLast" : "Juremi Profar",
    "nameSlug" : "juremi-profar-642282",
    "firstLastName" : "Juremi Profar",
    "lastFirstName" : "Profar, Juremi",
    "lastInitName" : "Profar, J",
    "initLastName" : "J Profar",
    "fullFMLName" : "Juremi Gregorius Profar",
    "fullLFMName" : "Profar, Juremi Gregorius",
    "strikeZoneTop" : 3.43,
    "strikeZoneBottom" : 1.5
  }, {
    "id" : 669274,
    "fullName" : "Edmond Americaan",
    "link" : "/api/v1/people/669274",
    "firstName" : "Edmond",
    "lastName" : "Americaan",
    "primaryNumber" : "89",
    "birthDate" : "1997-03-26",
    "currentAge" : 23,
    "birthCountry" : "Curacao",
    "height" : "6' 1\"",
    "weight" : 170,
    "active" : true,
    "primaryPosition" : {
      "code" : "8",
      "name" : "Outfielder",
      "type" : "Outfielder",
      "abbreviation" : "CF"
    },
    "useName" : "Edmond",
    "middleName" : "F.",
    "boxscoreName" : "Americaan",
    "gender" : "M",
    "isPlayer" : true,
    "isVerified" : false,
    "draftYear" : 2018,
    "batSide" : {
      "code" : "L",
      "description" : "Left"
    },
    "pitchHand" : {
      "code" : "L",
      "description" : "Left"
    },
    "nameFirstLast" : "Edmond Americaan",
    "nameSlug" : "edmond-americaan-669274",
    "firstLastName" : "Edmond Americaan",
    "lastFirstName" : "Americaan, Edmond",
    "lastInitName" : "Americaan, E",
    "initLastName" : "E Americaan",
    "fullFMLName" : "Edmond F. Americaan",
    "fullLFMName" : "Americaan, Edmond F.",
    "strikeZoneTop" : 3.411,
    "strikeZoneBottom" : 1.565
  }, {
    "id" : 665947,
    "fullName" : "Sherten Apostel",
    "link" : "/api/v1/people/665947",
    "firstName" : "Sherten",
    "lastName" : "Apostel",
    "primaryNumber" : "82",
    "birthDate" : "1999-03-11",
    "currentAge" : 21,
    "birthCity" : "Willemstad",
    "birthCountry" : "Curacao",
    "height" : "6' 4\"",
    "weight" : 200,
    "active" : true,
    "primaryPosition" : {
      "code" : "5",
      "name" : "Third Base",
      "type" : "Infielder",
      "abbreviation" : "3B"
    },
    "useName" : "Sherten",
    "middleName" : "Wimbert Ramiro",
    "boxscoreName" : "Apostel",
    "gender" : "M",
    "nameMatrilineal" : "Rollins",
    "isPlayer" : true,
    "isVerified" : true,
    "batSide" : {
      "code" : "R",
      "description" : "Right"
    },
    "pitchHand" : {
      "code" : "R",
      "description" : "Right"
    },
    "nameFirstLast" : "Sherten Apostel",
    "nameSlug" : "sherten-apostel-665947",
    "firstLastName" : "Sherten Apostel",
    "lastFirstName" : "Apostel, Sherten",
    "lastInitName" : "Apostel, S",
    "initLastName" : "S Apostel",
    "fullFMLName" : "Sherten Wimbert Ramiro Apostel",
    "fullLFMName" : "Apostel, Sherten Wimbert Ramiro",
    "strikeZoneTop" : 3.549,
    "strikeZoneBottom" : 1.627
  }, {
    "id" : 650851,
    "fullName" : "Tom de Blok",
    "link" : "/api/v1/people/650851",
    "firstName" : "Tom",
    "lastName" : "de Blok",
    "birthDate" : "1996-05-08",
    "currentAge" : 24,
    "birthCity" : "Amstelveen",
    "birthCountry" : "Netherlands",
    "height" : "6' 4\"",
    "weight" : 240,
    "active" : true,
    "primaryPosition" : {
      "code" : "1",
      "name" : "Pitcher",
      "type" : "Pitcher",
      "abbreviation" : "P"
    },
    "useName" : "Tom",
    "middleName" : "Robin",
    "boxscoreName" : "de Blok",
    "gender" : "M",
    "isPlayer" : true,
    "isVerified" : true,
    "batSide" : {
      "code" : "R",
      "description" : "Right"
    },
    "pitchHand" : {
      "code" : "R",
      "description" : "Right"
    },
    "nameFirstLast" : "Tom de Blok",
    "nameSlug" : "tom-de-blok-650851",
    "firstLastName" : "Tom de Blok",
    "lastFirstName" : "de Blok, Tom",
    "lastInitName" : "de Blok, T",
    "initLastName" : "T de Blok",
    "fullFMLName" : "Tom Robin de Blok",
    "fullLFMName" : "de Blok, Tom Robin",
    "strikeZoneTop" : 3.549,
    "strikeZoneBottom" : 1.627
  }, {
    "id" : 691829,
    "fullName" : "Jiorgeny Casimiri",
    "link" : "/api/v1/people/691829",
    "firstName" : "Jiorgeny",
    "lastName" : "Casimiri",
    "birthDate" : "2001-07-12",
    "currentAge" : 18,
    "birthCity" : "The Hague",
    "birthCountry" : "Netherlands",
    "height" : "6' 1\"",
    "weight" : 160,
    "active" : true,
    "primaryPosition" : {
      "code" : "1",
      "name" : "Pitcher",
      "type" : "Pitcher",
      "abbreviation" : "P"
    },
    "useName" : "Jiorgeny",
    "boxscoreName" : "Casimiri",
    "gender" : "M",
    "isPlayer" : true,
    "isVerified" : false,
    "batSide" : {
      "code" : "R",
      "description" : "Right"
    },
    "pitchHand" : {
      "code" : "R",
      "description" : "Right"
    },
    "nameFirstLast" : "Jiorgeny Casimiri",
    "nameSlug" : "jiorgeny-casimiri-691829",
    "firstLastName" : "Jiorgeny Casimiri",
    "lastFirstName" : "Casimiri, Jiorgeny",
    "lastInitName" : "Casimiri, J",
    "initLastName" : "J Casimiri",
    "fullFMLName" : "Jiorgeny  Casimiri",
    "fullLFMName" : "Casimiri, Jiorgeny",
    "strikeZoneTop" : 3.411,
    "strikeZoneBottom" : 1.565
  }, {
    "id" : 649955,
    "fullName" : "Hendrik Clementina",
    "link" : "/api/v1/people/649955",
    "firstName" : "Hendrik",
    "lastName" : "Clementina",
    "primaryNumber" : "33",
    "birthDate" : "1997-06-17",
    "currentAge" : 22,
    "birthCity" : "Willemstad",
    "birthCountry" : "Curacao",
    "height" : "6' 0\"",
    "weight" : 250,
    "active" : true,
    "primaryPosition" : {
      "code" : "2",
      "name" : "Catcher",
      "type" : "Catcher",
      "abbreviation" : "C"
    },
    "useName" : "Hendrik",
    "middleName" : "Jesus",
    "boxscoreName" : "Clementina",
    "gender" : "M",
    "nameMatrilineal" : "Ladera",
    "isPlayer" : true,
    "isVerified" : true,
    "batSide" : {
      "code" : "R",
      "description" : "Right"
    },
    "pitchHand" : {
      "code" : "R",
      "description" : "Right"
    },
    "nameFirstLast" : "Hendrik Clementina",
    "nameSlug" : "hendrik-clementina-649955",
    "firstLastName" : "Hendrik Clementina",
    "lastFirstName" : "Clementina, Hendrik",
    "lastInitName" : "Clementina, H",
    "initLastName" : "H Clementina",
    "fullFMLName" : "Hendrik Jesus Clementina",
    "fullLFMName" : "Clementina, Hendrik Jesus",
    "strikeZoneTop" : 3.371,
    "strikeZoneBottom" : 1.535
  }, {
    "id" : 676875,
    "fullName" : "Franklin Van Gurp",
    "link" : "/api/v1/people/676875",
    "firstName" : "Franklin",
    "lastName" : "Van Gurp",
    "birthDate" : "1995-10-26",
    "currentAge" : 24,
    "birthCity" : "Philipsburg",
    "birthCountry" : "Saint Martin",
    "height" : "6' 1\"",
    "weight" : 225,
    "active" : true,
    "primaryPosition" : {
      "code" : "1",
      "name" : "Pitcher",
      "type" : "Pitcher",
      "abbreviation" : "P"
    },
    "useName" : "Franklin",
    "boxscoreName" : "Van Gurp",
    "gender" : "M",
    "isPlayer" : true,
    "isVerified" : false,
    "draftYear" : 2017,
    "batSide" : {
      "code" : "R",
      "description" : "Right"
    },
    "pitchHand" : {
      "code" : "R",
      "description" : "Right"
    },
    "nameFirstLast" : "Franklin Van Gurp",
    "nameSlug" : "franklin-van-gurp-676875",
    "firstLastName" : "Franklin Van Gurp",
    "lastFirstName" : "Van Gurp, Franklin",
    "lastInitName" : "Van Gurp, F",
    "initLastName" : "F Van Gurp",
    "fullFMLName" : "Franklin Van Gurp",
    "fullLFMName" : "Van Gurp, Franklin",
    "strikeZoneTop" : 3.411,
    "strikeZoneBottom" : 1.565
  }, {
    "id" : 645291,
    "fullName" : "Kevin Josephina",
    "link" : "/api/v1/people/645291",
    "firstName" : "Kevin",
    "lastName" : "Josephina",
    "primaryNumber" : "95",
    "birthDate" : "1996-10-02",
    "currentAge" : 23,
    "birthCity" : "Willemstad",
    "birthCountry" : "Curacao",
    "height" : "6' 0\"",
    "weight" : 170,
    "active" : true,
    "primaryPosition" : {
      "code" : "I",
      "name" : "Infield",
      "type" : "Infielder",
      "abbreviation" : "IF"
    },
    "useName" : "Kevin",
    "middleName" : "Carl Michael",
    "boxscoreName" : "Josephina, K",
    "gender" : "M",
    "isPlayer" : true,
    "isVerified" : true,
    "batSide" : {
      "code" : "S",
      "description" : "Switch"
    },
    "pitchHand" : {
      "code" : "R",
      "description" : "Right"
    },
    "nameFirstLast" : "Kevin Josephina",
    "nameSlug" : "kevin-josephina-645291",
    "firstLastName" : "Kevin Josephina",
    "lastFirstName" : "Josephina, Kevin",
    "lastInitName" : "Josephina, K",
    "initLastName" : "K Josephina",
    "fullFMLName" : "Kevin Carl Michael Josephina",
    "fullLFMName" : "Josephina, Kevin Carl Michael",
    "strikeZoneTop" : 3.371,
    "strikeZoneBottom" : 1.535
  }, {
    "id" : 689168,
    "fullName" : "Orsen Josephina",
    "link" : "/api/v1/people/689168",
    "firstName" : "Orsen",
    "lastName" : "Josephina",
    "birthDate" : "1995-09-08",
    "currentAge" : 24,
    "birthCity" : "West Palm Beach",
    "birthStateProvince" : "FL",
    "birthCountry" : "USA",
    "height" : "6' 2\"",
    "weight" : 190,
    "active" : true,
    "primaryPosition" : {
      "code" : "1",
      "name" : "Pitcher",
      "type" : "Pitcher",
      "abbreviation" : "P"
    },
    "useName" : "Orsen",
    "middleName" : "Adriano Gisberto",
    "boxscoreName" : "Josephina",
    "gender" : "M",
    "isPlayer" : true,
    "isVerified" : true,
    "batSide" : {
      "code" : "R",
      "description" : "Right"
    },
    "pitchHand" : {
      "code" : "R",
      "description" : "Right"
    },
    "nameFirstLast" : "Orsen Josephina",
    "nameSlug" : "orsen-josephina-689168",
    "firstLastName" : "Orsen Josephina",
    "lastFirstName" : "Josephina, Orsen",
    "lastInitName" : "Josephina, O",
    "initLastName" : "O Josephina",
    "fullFMLName" : "Orsen Adriano Gisberto Josephina",
    "fullLFMName" : "Josephina, Orsen Adriano Gisberto",
    "strikeZoneTop" : 3.467,
    "strikeZoneBottom" : 1.589
  }, {
    "id" : 687850,
    "fullName" : "Junior Martina",
    "link" : "/api/v1/people/687850",
    "firstName" : "Francinel",
    "lastName" : "Martina",
    "birthDate" : "1997-12-12",
    "currentAge" : 22,
    "birthCity" : "Willemstad",
    "birthCountry" : "Curacao",
    "height" : "5' 11\"",
    "weight" : 190,
    "active" : true,
    "primaryPosition" : {
      "code" : "6",
      "name" : "Shortstop",
      "type" : "Infielder",
      "abbreviation" : "SS"
    },
    "useName" : "Junior",
    "middleName" : "Francisco",
    "boxscoreName" : "Martina",
    "gender" : "M",
    "isPlayer" : true,
    "isVerified" : true,
    "draftYear" : 2019,
    "batSide" : {
      "code" : "R",
      "description" : "Right"
    },
    "pitchHand" : {
      "code" : "R",
      "description" : "Right"
    },
    "nameFirstLast" : "Junior Martina",
    "nameSlug" : "junior-martina-687850",
    "firstLastName" : "Junior Martina",
    "lastFirstName" : "Martina, Junior",
    "lastInitName" : "Martina, F",
    "initLastName" : "F Martina",
    "fullFMLName" : "Francinel Francisco Martina",
    "fullLFMName" : "Martina, Francinel Francisco",
    "strikeZoneTop" : 3.319,
    "strikeZoneBottom" : 1.513
  }, {
    "id" : 660745,
    "fullName" : "Shean Michel",
    "link" : "/api/v1/people/660745",
    "firstName" : "Raysheandall",
    "lastName" : "Michel",
    "primaryNumber" : "92",
    "birthDate" : "1997-09-26",
    "currentAge" : 22,
    "birthCity" : "Willemstad",
    "birthCountry" : "Curacao",
    "height" : "5' 11\"",
    "weight" : 170,
    "active" : true,
    "primaryPosition" : {
      "code" : "O",
      "name" : "Outfield",
      "type" : "Outfielder",
      "abbreviation" : "OF"
    },
    "useName" : "Shean",
    "middleName" : "Juliandru Vernon",
    "boxscoreName" : "Michel",
    "gender" : "M",
    "isPlayer" : true,
    "isVerified" : false,
    "batSide" : {
      "code" : "R",
      "description" : "Right"
    },
    "pitchHand" : {
      "code" : "R",
      "description" : "Right"
    },
    "nameFirstLast" : "Shean Michel",
    "nameSlug" : "shean-michel-660745",
    "firstLastName" : "Shean Michel",
    "lastFirstName" : "Michel, Shean",
    "lastInitName" : "Michel, R",
    "initLastName" : "R Michel",
    "fullFMLName" : "Raysheandall Juliandru Vernon Michel",
    "fullLFMName" : "Michel, Raysheandall Juliandru Vernon",
    "strikeZoneTop" : 3.319,
    "strikeZoneBottom" : 1.513
  }, {
    "id" : 622362,
    "fullName" : "Chris Pieters",
    "link" : "/api/v1/people/622362",
    "firstName" : "Christopher",
    "lastName" : "Pieters",
    "primaryNumber" : "82",
    "birthDate" : "1994-09-21",
    "currentAge" : 25,
    "birthCity" : "Willemstad",
    "birthCountry" : "Curacao",
    "height" : "6' 3\"",
    "weight" : 185,
    "active" : true,
    "primaryPosition" : {
      "code" : "O",
      "name" : "Outfield",
      "type" : "Outfielder",
      "abbreviation" : "OF"
    },
    "useName" : "Chris",
    "middleName" : "Daniel",
    "boxscoreName" : "Pieters",
    "gender" : "M",
    "isPlayer" : true,
    "isVerified" : true,
    "batSide" : {
      "code" : "L",
      "description" : "Left"
    },
    "pitchHand" : {
      "code" : "L",
      "description" : "Left"
    },
    "nameFirstLast" : "Chris Pieters",
    "nameSlug" : "chris-pieters-622362",
    "firstLastName" : "Chris Pieters",
    "lastFirstName" : "Pieters, Chris",
    "lastInitName" : "Pieters, C",
    "initLastName" : "C Pieters",
    "fullFMLName" : "Christopher Daniel Pieters",
    "fullLFMName" : "Pieters, Christopher Daniel",
    "strikeZoneTop" : 3.49,
    "strikeZoneBottom" : 1.601
  }, {
    "id" : 678882,
    "fullName" : "Ceddanne Rafaela",
    "link" : "/api/v1/people/678882",
    "firstName" : "Ceddanne",
    "lastName" : "Rafaela",
    "birthDate" : "2000-09-18",
    "currentAge" : 19,
    "birthCity" : "Willemstad",
    "birthCountry" : "Curacao",
    "height" : "5' 8\"",
    "weight" : 145,
    "active" : true,
    "primaryPosition" : {
      "code" : "6",
      "name" : "Shortstop",
      "type" : "Infielder",
      "abbreviation" : "SS"
    },
    "useName" : "Ceddanne",
    "middleName" : "Chipper Nicasio Marte",
    "boxscoreName" : "Rafaela",
    "gender" : "M",
    "isPlayer" : true,
    "isVerified" : true,
    "batSide" : {
      "code" : "R",
      "description" : "Right"
    },
    "pitchHand" : {
      "code" : "R",
      "description" : "Right"
    },
    "nameFirstLast" : "Ceddanne Rafaela",
    "nameSlug" : "ceddanne-rafaela-678882",
    "firstLastName" : "Ceddanne Rafaela",
    "lastFirstName" : "Rafaela, Ceddanne",
    "lastInitName" : "Rafaela, C",
    "initLastName" : "C Rafaela",
    "fullFMLName" : "Ceddanne Chipper Nicasio Marte Rafaela",
    "fullLFMName" : "Rafaela, Ceddanne Chipper Nicasio Marte",
    "strikeZoneTop" : 3.26,
    "strikeZoneBottom" : 1.481
  }, {
    "id" : 682516,
    "fullName" : "Stephan Vidal",
    "link" : "/api/v1/people/682516",
    "firstName" : "Stephan",
    "lastName" : "Vidal",
    "birthDate" : "1996-04-04",
    "currentAge" : 24,
    "birthCity" : "Willemstad",
    "birthCountry" : "Curacao",
    "height" : "6' 1\"",
    "weight" : 215,
    "active" : true,
    "primaryPosition" : {
      "code" : "2",
      "name" : "Catcher",
      "type" : "Catcher",
      "abbreviation" : "C"
    },
    "useName" : "Stephan",
    "boxscoreName" : "Vidal",
    "gender" : "M",
    "isPlayer" : true,
    "isVerified" : false,
    "batSide" : {
      "code" : "R",
      "description" : "Right"
    },
    "pitchHand" : {
      "code" : "R",
      "description" : "Right"
    },
    "nameFirstLast" : "Stephan Vidal",
    "nameSlug" : "stephan-vidal-682516",
    "firstLastName" : "Stephan Vidal",
    "lastFirstName" : "Vidal, Stephan",
    "lastInitName" : "Vidal, S",
    "initLastName" : "S Vidal",
    "fullFMLName" : "Stephan  Vidal",
    "fullLFMName" : "Vidal, Stephan",
    "strikeZoneTop" : 3.411,
    "strikeZoneBottom" : 1.565
  }, {
    "id" : 666635,
    "fullName" : "Jonathan Willems",
    "link" : "/api/v1/people/666635",
    "firstName" : "Jonathan",
    "lastName" : "Willems",
    "birthDate" : "1998-11-07",
    "currentAge" : 21,
    "birthCity" : "Willemstad",
    "birthCountry" : "Curacao",
    "height" : "5' 11\"",
    "weight" : 190,
    "active" : true,
    "primaryPosition" : {
      "code" : "I",
      "name" : "Infield",
      "type" : "Infielder",
      "abbreviation" : "IF"
    },
    "useName" : "Jonathan",
    "middleName" : "Cornelis",
    "boxscoreName" : "Willems",
    "gender" : "M",
    "isPlayer" : true,
    "isVerified" : false,
    "batSide" : {
      "code" : "R",
      "description" : "Right"
    },
    "pitchHand" : {
      "code" : "R",
      "description" : "Right"
    },
    "nameFirstLast" : "Jonathan Willems",
    "nameSlug" : "jonathan-willems-666635",
    "firstLastName" : "Jonathan Willems",
    "lastFirstName" : "Willems, Jonathan",
    "lastInitName" : "Willems, J",
    "initLastName" : "J Willems",
    "fullFMLName" : "Jonathan Cornelis Willems",
    "fullLFMName" : "Willems, Jonathan Cornelis",
    "strikeZoneTop" : 3.319,
    "strikeZoneBottom" : 1.513
  }, {
    "id" : 661250,
    "fullName" : "Izzy Wilson",
    "link" : "/api/v1/people/661250",
    "firstName" : "Isranel",
    "lastName" : "Wilson",
    "birthDate" : "1998-03-06",
    "currentAge" : 22,
    "birthCity" : "Saint Maarten",
    "birthCountry" : "Netherlands Antilles",
    "height" : "6' 3\"",
    "weight" : 185,
    "active" : true,
    "primaryPosition" : {
      "code" : "O",
      "name" : "Outfield",
      "type" : "Outfielder",
      "abbreviation" : "OF"
    },
    "useName" : "Izzy",
    "boxscoreName" : "Wilson, I",
    "gender" : "M",
    "nameMatrilineal" : "Paula",
    "isPlayer" : true,
    "isVerified" : false,
    "batSide" : {
      "code" : "L",
      "description" : "Left"
    },
    "pitchHand" : {
      "code" : "R",
      "description" : "Right"
    },
    "nameFirstLast" : "Izzy Wilson",
    "nameSlug" : "izzy-wilson-661250",
    "firstLastName" : "Izzy Wilson",
    "lastFirstName" : "Wilson, Izzy",
    "lastInitName" : "Wilson, I",
    "initLastName" : "I Wilson",
    "fullFMLName" : "Izzy Wilson",
    "fullLFMName" : "Wilson, Izzy",
    "strikeZoneTop" : 3.49,
    "strikeZoneBottom" : 1.601
  }, {
    "id" : 677642,
    "fullName" : "Givaine Basilia",
    "link" : "/api/v1/people/677642",
    "firstName" : "Givaine",
    "lastName" : "Basilia",
    "birthDate" : "2000-06-22",
    "currentAge" : 19,
    "birthCity" : "Willemstad",
    "birthCountry" : "Curacao",
    "height" : "6' 1\"",
    "weight" : 160,
    "active" : true,
    "primaryPosition" : {
      "code" : "6",
      "name" : "Shortstop",
      "type" : "Infielder",
      "abbreviation" : "SS"
    },
    "useName" : "Givaine",
    "middleName" : "Nathanael",
    "boxscoreName" : "Basilia",
    "gender" : "M",
    "isPlayer" : true,
    "isVerified" : true,
    "batSide" : {
      "code" : "R",
      "description" : "Right"
    },
    "pitchHand" : {
      "code" : "R",
      "description" : "Right"
    },
    "nameFirstLast" : "Givaine Basilia",
    "nameSlug" : "givaine-basilia-677642",
    "firstLastName" : "Givaine Basilia",
    "lastFirstName" : "Basilia, Givaine",
    "lastInitName" : "Basilia, G",
    "initLastName" : "G Basilia",
    "fullFMLName" : "Givaine Nathanael Basilia",
    "fullLFMName" : "Basilia, Givaine Nathanael",
    "strikeZoneTop" : 3.411,
    "strikeZoneBottom" : 1.565
  }, {
    "id" : 678281,
    "fullName" : "Donny Breek",
    "link" : "/api/v1/people/678281",
    "firstName" : "Donny",
    "lastName" : "Breek",
    "birthDate" : "1999-11-08",
    "currentAge" : 20,
    "birthCity" : "Amsterdam",
    "birthCountry" : "Netherlands",
    "height" : "6' 2\"",
    "weight" : 205,
    "active" : true,
    "primaryPosition" : {
      "code" : "1",
      "name" : "Pitcher",
      "type" : "Pitcher",
      "abbreviation" : "P"
    },
    "useName" : "Donny",
    "boxscoreName" : "Breek",
    "gender" : "M",
    "isPlayer" : true,
    "isVerified" : true,
    "batSide" : {
      "code" : "R",
      "description" : "Right"
    },
    "pitchHand" : {
      "code" : "R",
      "description" : "Right"
    },
    "nameFirstLast" : "Donny Breek",
    "nameSlug" : "donny-breek-678281",
    "firstLastName" : "Donny Breek",
    "lastFirstName" : "Breek, Donny",
    "lastInitName" : "Breek, D",
    "initLastName" : "D Breek",
    "fullFMLName" : "Donny  Breek",
    "fullLFMName" : "Breek, Donny",
    "strikeZoneTop" : 3.467,
    "strikeZoneBottom" : 1.589
  }, {
    "id" : 683666,
    "fullName" : "Denzel Bryson",
    "link" : "/api/v1/people/683666",
    "firstName" : "Denzel",
    "lastName" : "Bryson",
    "birthDate" : "2000-09-26",
    "currentAge" : 19,
    "birthCity" : "Oranjestad",
    "birthCountry" : "Aruba",
    "height" : "5' 11\"",
    "weight" : 185,
    "active" : true,
    "primaryPosition" : {
      "code" : "2",
      "name" : "Catcher",
      "type" : "Catcher",
      "abbreviation" : "C"
    },
    "useName" : "Denzel",
    "middleName" : "Youssri Ignacio",
    "boxscoreName" : "Bryson",
    "gender" : "M",
    "isPlayer" : true,
    "isVerified" : true,
    "batSide" : {
      "code" : "R",
      "description" : "Right"
    },
    "pitchHand" : {
      "code" : "R",
      "description" : "Right"
    },
    "nameFirstLast" : "Denzel Bryson",
    "nameSlug" : "denzel-bryson-683666",
    "firstLastName" : "Denzel Bryson",
    "lastFirstName" : "Bryson, Denzel",
    "lastInitName" : "Bryson, D",
    "initLastName" : "D Bryson",
    "fullFMLName" : "Denzel Youssri Ignacio Bryson",
    "fullLFMName" : "Bryson, Denzel Youssri Ignacio",
    "strikeZoneTop" : 3.319,
    "strikeZoneBottom" : 1.513
  }, {
    "id" : 683408,
    "fullName" : "Darryl Collins",
    "link" : "/api/v1/people/683408",
    "firstName" : "Darryl",
    "lastName" : "Collins",
    "birthDate" : "2001-09-16",
    "currentAge" : 18,
    "birthCity" : "Spijkenisse",
    "birthCountry" : "Netherlands",
    "height" : "6' 2\"",
    "weight" : 185,
    "active" : true,
    "primaryPosition" : {
      "code" : "O",
      "name" : "Outfield",
      "type" : "Outfielder",
      "abbreviation" : "OF"
    },
    "useName" : "Darryl",
    "middleName" : "James",
    "boxscoreName" : "Collins",
    "gender" : "M",
    "isPlayer" : true,
    "isVerified" : true,
    "batSide" : {
      "code" : "L",
      "description" : "Left"
    },
    "pitchHand" : {
      "code" : "R",
      "description" : "Right"
    },
    "nameFirstLast" : "Darryl Collins",
    "nameSlug" : "darryl-collins-683408",
    "firstLastName" : "Darryl Collins",
    "lastFirstName" : "Collins, Darryl",
    "lastInitName" : "Collins, D",
    "initLastName" : "D Collins",
    "fullFMLName" : "Darryl James Collins",
    "fullLFMName" : "Collins, Darryl James",
    "strikeZoneTop" : 3.467,
    "strikeZoneBottom" : 1.589
  }, {
    "id" : 687677,
    "fullName" : "Arij Fransen",
    "link" : "/api/v1/people/687677",
    "firstName" : "Arij",
    "lastName" : "Fransen",
    "birthDate" : "2001-05-20",
    "currentAge" : 18,
    "birthCity" : "Deventer",
    "birthCountry" : "Netherlands",
    "height" : "6' 3\"",
    "weight" : 190,
    "active" : true,
    "primaryPosition" : {
      "code" : "1",
      "name" : "Pitcher",
      "type" : "Pitcher",
      "abbreviation" : "P"
    },
    "useName" : "Arij",
    "boxscoreName" : "Fransen",
    "gender" : "M",
    "isPlayer" : true,
    "isVerified" : true,
    "batSide" : {
      "code" : "R",
      "description" : "Right"
    },
    "pitchHand" : {
      "code" : "R",
      "description" : "Right"
    },
    "nameFirstLast" : "Arij Fransen",
    "nameSlug" : "arij-fransen-687677",
    "firstLastName" : "Arij Fransen",
    "lastFirstName" : "Fransen, Arij",
    "lastInitName" : "Fransen, A",
    "initLastName" : "A Fransen",
    "fullFMLName" : "Arij  Fransen",
    "fullLFMName" : "Fransen, Arij",
    "strikeZoneTop" : 3.49,
    "strikeZoneBottom" : 1.601
  }, {
    "id" : 680884,
    "fullName" : "Aldrich De Jongh",
    "link" : "/api/v1/people/680884",
    "firstName" : "Aldrich",
    "lastName" : "De Jongh",
    "birthDate" : "1998-09-01",
    "currentAge" : 21,
    "birthCity" : "Willemstad",
    "birthCountry" : "Curacao",
    "height" : "5' 9\"",
    "weight" : 160,
    "active" : true,
    "primaryPosition" : {
      "code" : "O",
      "name" : "Outfield",
      "type" : "Outfielder",
      "abbreviation" : "OF"
    },
    "useName" : "Aldrich",
    "boxscoreName" : "De Jongh",
    "gender" : "M",
    "isPlayer" : true,
    "isVerified" : false,
    "draftYear" : 2018,
    "batSide" : {
      "code" : "L",
      "description" : "Left"
    },
    "pitchHand" : {
      "code" : "R",
      "description" : "Right"
    },
    "nameFirstLast" : "Aldrich De Jongh",
    "nameSlug" : "aldrich-de-jongh-680884",
    "firstLastName" : "Aldrich De Jongh",
    "lastFirstName" : "De Jongh, Aldrich",
    "lastInitName" : "De Jongh, A",
    "initLastName" : "A De Jongh",
    "fullFMLName" : "Aldrich  De Jongh",
    "fullLFMName" : "De Jongh, Aldrich",
    "strikeZoneTop" : 3.285,
    "strikeZoneBottom" : 1.487
  }, {
    "id" : 678427,
    "fullName" : "Richgelon Juliana",
    "link" : "/api/v1/people/678427",
    "firstName" : "Richgelon",
    "lastName" : "Juliana",
    "birthDate" : "2000-05-30",
    "currentAge" : 19,
    "birthCity" : "Willemstad",
    "birthCountry" : "Curacao",
    "height" : "6' 0\"",
    "weight" : 170,
    "active" : true,
    "primaryPosition" : {
      "code" : "8",
      "name" : "Outfielder",
      "type" : "Outfielder",
      "abbreviation" : "CF"
    },
    "useName" : "Richgelon",
    "middleName" : "Natanael",
    "boxscoreName" : "Juliana",
    "gender" : "M",
    "nameMatrilineal" : "Lourens",
    "isPlayer" : true,
    "isVerified" : true,
    "batSide" : {
      "code" : "R",
      "description" : "Right"
    },
    "pitchHand" : {
      "code" : "R",
      "description" : "Right"
    },
    "nameFirstLast" : "Richgelon Juliana",
    "nameSlug" : "richgelon-juliana-678427",
    "firstLastName" : "Richgelon Juliana",
    "lastFirstName" : "Juliana, Richgelon",
    "lastInitName" : "Juliana, R",
    "initLastName" : "R Juliana",
    "fullFMLName" : "Richgelon Natanael Juliana",
    "fullLFMName" : "Juliana, Richgelon Natanael",
    "strikeZoneTop" : 3.371,
    "strikeZoneBottom" : 1.535
  }, {
    "id" : 672561,
    "fullName" : "Makesiondon Kelkboom",
    "link" : "/api/v1/people/672561",
    "firstName" : "Makesiondon",
    "lastName" : "Kelkboom",
    "birthDate" : "2000-07-12",
    "currentAge" : 19,
    "birthCity" : "Leiden",
    "birthCountry" : "Netherlands",
    "height" : "5' 11\"",
    "weight" : 152,
    "active" : true,
    "primaryPosition" : {
      "code" : "6",
      "name" : "Shortstop",
      "type" : "Infielder",
      "abbreviation" : "SS"
    },
    "useName" : "Makesiondon",
    "middleName" : "Juroney",
    "boxscoreName" : "Kelkboom",
    "gender" : "M",
    "isPlayer" : true,
    "isVerified" : true,
    "batSide" : {
      "code" : "R",
      "description" : "Right"
    },
    "pitchHand" : {
      "code" : "R",
      "description" : "Right"
    },
    "nameFirstLast" : "Makesiondon Kelkboom",
    "nameSlug" : "makesiondon-kelkboom-672561",
    "firstLastName" : "Makesiondon Kelkboom",
    "lastFirstName" : "Kelkboom, Makesiondon",
    "lastInitName" : "Kelkboom, M",
    "initLastName" : "M Kelkboom",
    "fullFMLName" : "Makesiondon Juroney Kelkboom",
    "fullLFMName" : "Kelkboom, Makesiondon Juroney",
    "strikeZoneTop" : 3.319,
    "strikeZoneBottom" : 1.513
  }, {
    "id" : 677804,
    "fullName" : "Eric Mendez",
    "link" : "/api/v1/people/677804",
    "firstName" : "Eric",
    "lastName" : "Mendez",
    "birthDate" : "1999-12-03",
    "currentAge" : 20,
    "birthCity" : "Cura Cabai",
    "birthCountry" : "Aruba",
    "height" : "6' 0\"",
    "weight" : 175,
    "active" : true,
    "primaryPosition" : {
      "code" : "1",
      "name" : "Pitcher",
      "type" : "Pitcher",
      "abbreviation" : "P"
    },
    "useName" : "Eric",
    "middleName" : "Ernesto",
    "boxscoreName" : "Mendez",
    "gender" : "M",
    "nameMatrilineal" : "Matos",
    "isPlayer" : true,
    "isVerified" : true,
    "batSide" : {
      "code" : "R",
      "description" : "Right"
    },
    "pitchHand" : {
      "code" : "R",
      "description" : "Right"
    },
    "nameFirstLast" : "Eric Mendez",
    "nameSlug" : "eric-mendez-677804",
    "firstLastName" : "Eric Mendez",
    "lastFirstName" : "Mendez, Eric",
    "lastInitName" : "Mendez, E",
    "initLastName" : "E Mendez",
    "fullFMLName" : "Eric Ernesto Mendez",
    "fullLFMName" : "Mendez, Eric Ernesto",
    "strikeZoneTop" : 3.371,
    "strikeZoneBottom" : 1.535
  }, {
    "id" : 680634,
    "fullName" : "Tilsaimy Melfor",
    "link" : "/api/v1/people/680634",
    "firstName" : "Tilsaimy",
    "lastName" : "Melfor",
    "birthDate" : "2001-02-14",
    "currentAge" : 19,
    "birthCity" : "Willemstad",
    "birthCountry" : "Curacao",
    "height" : "6' 0\"",
    "weight" : 183,
    "active" : true,
    "primaryPosition" : {
      "code" : "5",
      "name" : "Third Base",
      "type" : "Infielder",
      "abbreviation" : "3B"
    },
    "useName" : "Tilsaimy",
    "middleName" : "Fabian Valentino",
    "boxscoreName" : "Melfor",
    "gender" : "M",
    "isPlayer" : true,
    "isVerified" : true,
    "batSide" : {
      "code" : "R",
      "description" : "Right"
    },
    "pitchHand" : {
      "code" : "R",
      "description" : "Right"
    },
    "nameFirstLast" : "Tilsaimy Melfor",
    "nameSlug" : "tilsaimy-melfor-680634",
    "firstLastName" : "Tilsaimy Melfor",
    "lastFirstName" : "Melfor, Tilsaimy",
    "lastInitName" : "Melfor, T",
    "initLastName" : "T Melfor",
    "fullFMLName" : "Tilsaimy Fabian Valentino Melfor",
    "fullLFMName" : "Melfor, Tilsaimy Fabian Valentino",
    "strikeZoneTop" : 3.371,
    "strikeZoneBottom" : 1.535
  }, {
    "id" : 691828,
    "fullName" : "Sem Robberse",
    "link" : "/api/v1/people/691828",
    "firstName" : "Sem",
    "lastName" : "Robberse",
    "birthDate" : "2001-10-12",
    "currentAge" : 18,
    "birthCity" : "Zeist",
    "birthCountry" : "Netherlands",
    "height" : "6' 1\"",
    "weight" : 160,
    "active" : true,
    "primaryPosition" : {
      "code" : "1",
      "name" : "Pitcher",
      "type" : "Pitcher",
      "abbreviation" : "P"
    },
    "useName" : "Sem",
    "boxscoreName" : "Robberse",
    "gender" : "M",
    "isPlayer" : true,
    "isVerified" : true,
    "batSide" : {
      "code" : "R",
      "description" : "Right"
    },
    "pitchHand" : {
      "code" : "R",
      "description" : "Right"
    },
    "nameFirstLast" : "Sem Robberse",
    "nameSlug" : "sem-robberse-691828",
    "firstLastName" : "Sem Robberse",
    "lastFirstName" : "Robberse, Sem",
    "lastInitName" : "Robberse, S",
    "initLastName" : "S Robberse",
    "fullFMLName" : "Sem  Robberse",
    "fullLFMName" : "Robberse, Sem",
    "strikeZoneTop" : 3.411,
    "strikeZoneBottom" : 1.565
  }, {
    "id" : 681606,
    "fullName" : "Nigel Calmes",
    "link" : "/api/v1/people/681606",
    "firstName" : "Nigel",
    "lastName" : "Calmes",
    "birthDate" : "1999-09-21",
    "currentAge" : 20,
    "birthCountry" : "Aruba",
    "height" : "6' 1\"",
    "weight" : 175,
    "active" : true,
    "primaryPosition" : {
      "code" : "2",
      "name" : "Catcher",
      "type" : "Catcher",
      "abbreviation" : "C"
    },
    "useName" : "Nigel",
    "boxscoreName" : "Calmes",
    "gender" : "M",
    "isPlayer" : true,
    "isVerified" : false,
    "batSide" : {
      "code" : "R",
      "description" : "Right"
    },
    "pitchHand" : {
      "code" : "R",
      "description" : "Right"
    },
    "nameFirstLast" : "Nigel Calmes",
    "nameSlug" : "nigel-calmes-681606",
    "firstLastName" : "Nigel Calmes",
    "lastFirstName" : "Calmes, Nigel",
    "lastInitName" : "Calmes, N",
    "initLastName" : "N Calmes",
    "fullFMLName" : "Nigel  Calmes",
    "fullLFMName" : "Calmes, Nigel",
    "strikeZoneTop" : 3.411,
    "strikeZoneBottom" : 1.565
  }, {
    "id" : 679968,
    "fullName" : "Jerrick Francees",
    "link" : "/api/v1/people/679968",
    "firstName" : "Jerrick",
    "lastName" : "Francees",
    "birthDate" : "2000-05-18",
    "currentAge" : 19,
    "birthCity" : "Oranjestad",
    "birthCountry" : "Aruba",
    "height" : "6' 0\"",
    "weight" : 188,
    "active" : true,
    "primaryPosition" : {
      "code" : "4",
      "name" : "Second Base",
      "type" : "Infielder",
      "abbreviation" : "2B"
    },
    "useName" : "Jerrick",
    "middleName" : "Benjamin",
    "boxscoreName" : "Francees",
    "gender" : "M",
    "isPlayer" : true,
    "isVerified" : true,
    "batSide" : {
      "code" : "R",
      "description" : "Right"
    },
    "pitchHand" : {
      "code" : "R",
      "description" : "Right"
    },
    "nameFirstLast" : "Jerrick Francees",
    "nameSlug" : "jerrick-francees-679968",
    "firstLastName" : "Jerrick Francees",
    "lastFirstName" : "Francees, Jerrick",
    "lastInitName" : "Francees, J",
    "initLastName" : "J Francees",
    "fullFMLName" : "Jerrick Benjamin Francees",
    "fullLFMName" : "Francees, Jerrick Benjamin",
    "strikeZoneTop" : 3.371,
    "strikeZoneBottom" : 1.535
  }, {
    "id" : 683398,
    "fullName" : "Faysel Gregorio",
    "link" : "/api/v1/people/683398",
    "firstName" : "Faysel",
    "lastName" : "Gregorio",
    "birthDate" : "2002-05-09",
    "currentAge" : 17,
    "birthCity" : "Willemstad",
    "birthCountry" : "Curacao",
    "height" : "6' 2\"",
    "weight" : 150,
    "active" : true,
    "primaryPosition" : {
      "code" : "1",
      "name" : "Pitcher",
      "type" : "Pitcher",
      "abbreviation" : "P"
    },
    "useName" : "Faysel",
    "middleName" : "Alexander",
    "boxscoreName" : "Gregorio",
    "gender" : "M",
    "isPlayer" : true,
    "isVerified" : true,
    "batSide" : {
      "code" : "R",
      "description" : "Right"
    },
    "pitchHand" : {
      "code" : "R",
      "description" : "Right"
    },
    "nameFirstLast" : "Faysel Gregorio",
    "nameSlug" : "faysel-gregorio-683398",
    "firstLastName" : "Faysel Gregorio",
    "lastFirstName" : "Gregorio, Faysel",
    "lastInitName" : "Gregorio, F",
    "initLastName" : "F Gregorio",
    "fullFMLName" : "Faysel Alexander Gregorio",
    "fullLFMName" : "Gregorio, Faysel Alexander",
    "strikeZoneTop" : 3.467,
    "strikeZoneBottom" : 1.589
  }, {
    "id" : 683393,
    "fullName" : "J'Rudjeanon Isenia",
    "link" : "/api/v1/people/683393",
    "firstName" : "J'Rudjeanon",
    "lastName" : "Isenia",
    "birthDate" : "2001-12-07",
    "currentAge" : 18,
    "birthCity" : "Willemstad",
    "birthCountry" : "Curacao",
    "height" : "6' 1\"",
    "weight" : 185,
    "active" : true,
    "primaryPosition" : {
      "code" : "8",
      "name" : "Outfielder",
      "type" : "Outfielder",
      "abbreviation" : "CF"
    },
    "useName" : "J'Rudjeanon",
    "middleName" : "Ambrosio David",
    "boxscoreName" : "Isenia",
    "gender" : "M",
    "isPlayer" : true,
    "isVerified" : true,
    "pronunciation" : "ROOD-juh-nawn EE-sen-ya",
    "batSide" : {
      "code" : "R",
      "description" : "Right"
    },
    "pitchHand" : {
      "code" : "R",
      "description" : "Right"
    },
    "nameFirstLast" : "J'Rudjeanon Isenia",
    "nameSlug" : "j-rudjeanon-isenia-683393",
    "firstLastName" : "J'Rudjeanon Isenia",
    "lastFirstName" : "Isenia, J'Rudjeanon",
    "lastInitName" : "Isenia, J",
    "initLastName" : "J Isenia",
    "fullFMLName" : "J'Rudjeanon Ambrosio David Isenia",
    "fullLFMName" : "Isenia, J'Rudjeanon Ambrosio David",
    "strikeZoneTop" : 3.411,
    "strikeZoneBottom" : 1.565
  }, {
    "id" : 682888,
    "fullName" : "Cal Maduro",
    "link" : "/api/v1/people/682888",
    "firstName" : "Cal",
    "lastName" : "Maduro",
    "birthDate" : "2001-10-25",
    "currentAge" : 18,
    "birthCity" : "Oranjestad",
    "birthCountry" : "Aruba",
    "height" : "6' 0\"",
    "weight" : 165,
    "active" : true,
    "primaryPosition" : {
      "code" : "1",
      "name" : "Pitcher",
      "type" : "Pitcher",
      "abbreviation" : "P"
    },
    "useName" : "Cal",
    "middleName" : "Fernando",
    "boxscoreName" : "Maduro",
    "gender" : "M",
    "isPlayer" : true,
    "isVerified" : true,
    "batSide" : {
      "code" : "R",
      "description" : "Right"
    },
    "pitchHand" : {
      "code" : "R",
      "description" : "Right"
    },
    "nameFirstLast" : "Cal Maduro",
    "nameSlug" : "cal-maduro-682888",
    "firstLastName" : "Cal Maduro",
    "lastFirstName" : "Maduro, Cal",
    "lastInitName" : "Maduro, C",
    "initLastName" : "C Maduro",
    "fullFMLName" : "Cal Fernando Maduro",
    "fullLFMName" : "Maduro, Cal Fernando",
    "strikeZoneTop" : 3.371,
    "strikeZoneBottom" : 1.535
  }, {
    "id" : 683430,
    "fullName" : "Denverick Martines",
    "link" : "/api/v1/people/683430",
    "firstName" : "Denverick",
    "lastName" : "Martines",
    "birthDate" : "2001-05-31",
    "currentAge" : 18,
    "birthCity" : "Willemstad",
    "birthCountry" : "Curacao",
    "height" : "6' 0\"",
    "weight" : 170,
    "active" : true,
    "primaryPosition" : {
      "code" : "1",
      "name" : "Pitcher",
      "type" : "Pitcher",
      "abbreviation" : "P"
    },
    "useName" : "Denverick",
    "middleName" : "Ezequiel",
    "boxscoreName" : "Martines",
    "gender" : "M",
    "isPlayer" : true,
    "isVerified" : true,
    "batSide" : {
      "code" : "L",
      "description" : "Left"
    },
    "pitchHand" : {
      "code" : "L",
      "description" : "Left"
    },
    "nameFirstLast" : "Denverick Martines",
    "nameSlug" : "denverick-martines-683430",
    "firstLastName" : "Denverick Martines",
    "lastFirstName" : "Martines, Denverick",
    "lastInitName" : "Martines, D",
    "initLastName" : "D Martines",
    "fullFMLName" : "Denverick Ezequiel Martines",
    "fullLFMName" : "Martines, Denverick Ezequiel",
    "strikeZoneTop" : 3.371,
    "strikeZoneBottom" : 1.535
  }, {
    "id" : 682654,
    "fullName" : "Rainer Polonius",
    "link" : "/api/v1/people/682654",
    "firstName" : "Rainer",
    "lastName" : "Polonius",
    "birthDate" : "2001-09-24",
    "currentAge" : 18,
    "birthCity" : "Willemstad",
    "birthCountry" : "Curacao",
    "height" : "5' 11\"",
    "weight" : 147,
    "active" : true,
    "primaryPosition" : {
      "code" : "6",
      "name" : "Shortstop",
      "type" : "Infielder",
      "abbreviation" : "SS"
    },
    "useName" : "Rainer",
    "middleName" : "Kendrick",
    "boxscoreName" : "Polonius",
    "gender" : "M",
    "isPlayer" : true,
    "isVerified" : false,
    "batSide" : {
      "code" : "L",
      "description" : "Left"
    },
    "pitchHand" : {
      "code" : "R",
      "description" : "Right"
    },
    "nameFirstLast" : "Rainer Polonius",
    "nameSlug" : "rainer-polonius-682654",
    "firstLastName" : "Rainer Polonius",
    "lastFirstName" : "Polonius, Rainer",
    "lastInitName" : "Polonius, R",
    "initLastName" : "R Polonius",
    "fullFMLName" : "Rainer Kendrick Polonius",
    "fullLFMName" : "Polonius, Rainer Kendrick",
    "strikeZoneTop" : 3.319,
    "strikeZoneBottom" : 1.513
  }, {
    "id" : 682651,
    "fullName" : "Ryson Polonius",
    "link" : "/api/v1/people/682651",
    "firstName" : "Ryson",
    "lastName" : "Polonius",
    "birthDate" : "2001-09-24",
    "currentAge" : 18,
    "birthCity" : "Willemstad",
    "birthCountry" : "Curacao",
    "height" : "5' 11\"",
    "weight" : 147,
    "active" : true,
    "primaryPosition" : {
      "code" : "6",
      "name" : "Shortstop",
      "type" : "Infielder",
      "abbreviation" : "SS"
    },
    "useName" : "Ryson",
    "middleName" : "Rolando",
    "boxscoreName" : "Polonius",
    "gender" : "M",
    "isPlayer" : true,
    "isVerified" : false,
    "batSide" : {
      "code" : "L",
      "description" : "Left"
    },
    "pitchHand" : {
      "code" : "R",
      "description" : "Right"
    },
    "nameFirstLast" : "Ryson Polonius",
    "nameSlug" : "ryson-polonius-682651",
    "firstLastName" : "Ryson Polonius",
    "lastFirstName" : "Polonius, Ryson",
    "lastInitName" : "Polonius, R",
    "initLastName" : "R Polonius",
    "fullFMLName" : "Ryson Rolando Polonius",
    "fullLFMName" : "Polonius, Ryson Rolando",
    "strikeZoneTop" : 3.319,
    "strikeZoneBottom" : 1.513
  }, {
    "id" : 678799,
    "fullName" : "Brandon Rincones",
    "link" : "/api/v1/people/678799",
    "firstName" : "Brandon",
    "lastName" : "Rincones",
    "birthDate" : "2000-10-01",
    "currentAge" : 19,
    "birthCity" : "Oranjestad",
    "birthCountry" : "Aruba",
    "height" : "5' 9\"",
    "weight" : 145,
    "active" : true,
    "primaryPosition" : {
      "code" : "6",
      "name" : "Shortstop",
      "type" : "Infielder",
      "abbreviation" : "SS"
    },
    "useName" : "Brandon",
    "middleName" : "Yuwin",
    "boxscoreName" : "Rincones",
    "gender" : "M",
    "isPlayer" : true,
    "isVerified" : true,
    "batSide" : {
      "code" : "R",
      "description" : "Right"
    },
    "pitchHand" : {
      "code" : "R",
      "description" : "Right"
    },
    "nameFirstLast" : "Brandon Rincones",
    "nameSlug" : "brandon-rincones-678799",
    "firstLastName" : "Brandon Rincones",
    "lastFirstName" : "Rincones, Brandon",
    "lastInitName" : "Rincones, B",
    "initLastName" : "B Rincones",
    "fullFMLName" : "Brandon Yuwin Rincones",
    "fullLFMName" : "Rincones, Brandon Yuwin",
    "strikeZoneTop" : 3.285,
    "strikeZoneBottom" : 1.487
  }, {
    "id" : 678751,
    "fullName" : "Rushenten Tomsjansen",
    "link" : "/api/v1/people/678751",
    "firstName" : "Rushenten",
    "lastName" : "Tomsjansen",
    "birthDate" : "2001-05-14",
    "currentAge" : 18,
    "birthCity" : "Dordrecht",
    "birthCountry" : "Netherlands",
    "height" : "6' 0\"",
    "weight" : 150,
    "active" : true,
    "primaryPosition" : {
      "code" : "O",
      "name" : "Outfield",
      "type" : "Outfielder",
      "abbreviation" : "OF"
    },
    "useName" : "Rushenten",
    "middleName" : "Laybert Apostel",
    "boxscoreName" : "Tomsjansen",
    "gender" : "M",
    "isPlayer" : true,
    "isVerified" : false,
    "batSide" : {
      "code" : "R",
      "description" : "Right"
    },
    "pitchHand" : {
      "code" : "R",
      "description" : "Right"
    },
    "nameFirstLast" : "Rushenten Tomsjansen",
    "nameSlug" : "rushenten-tomsjansen-678751",
    "firstLastName" : "Rushenten Tomsjansen",
    "lastFirstName" : "Tomsjansen, Rushenten",
    "lastInitName" : "Tomsjansen, R",
    "initLastName" : "R Tomsjansen",
    "fullFMLName" : "Rushenten Laybert Apostel Tomsjansen",
    "fullLFMName" : "Tomsjansen, Rushenten Laybert Apostel",
    "strikeZoneTop" : 3.371,
    "strikeZoneBottom" : 1.535
  }, {
    "id" : 645277,
    "fullName" : "Ozzie Albies",
    "link" : "/api/v1/people/645277",
    "firstName" : "Ozhaino",
    "lastName" : "Albies",
    "primaryNumber" : "1",
    "birthDate" : "1997-01-07",
    "currentAge" : 23,
    "birthCity" : "Willemstad",
    "birthCountry" : "Curacao",
    "height" : "5' 8\"",
    "weight" : 165,
    "active" : true,
    "primaryPosition" : {
      "code" : "4",
      "name" : "Second Base",
      "type" : "Infielder",
      "abbreviation" : "2B"
    },
    "useName" : "Ozzie",
    "middleName" : "Jurdy Jiandro",
    "boxscoreName" : "Albies",
    "nickName" : "Bolly",
    "gender" : "M",
    "isPlayer" : true,
    "isVerified" : true,
    "stats" : [ {
      "type" : {
        "displayName" : "season"
      },
      "group" : {
        "displayName" : "hitting"
      },
      "exemptions" : [ ],
      "splits" : [ {
        "season" : "2019",
        "stat" : {
          "gamesPlayed" : 160,
          "groundOuts" : 149,
          "airOuts" : 194,
          "runs" : 102,
          "doubles" : 43,
          "triples" : 8,
          "homeRuns" : 24,
          "strikeOuts" : 112,
          "baseOnBalls" : 54,
          "intentionalWalks" : 6,
          "hits" : 189,
          "hitByPitch" : 4,
          "avg" : ".295",
          "atBats" : 640,
          "obp" : ".352",
          "slg" : ".500",
          "ops" : ".852",
          "caughtStealing" : 4,
          "stolenBases" : 15,
          "stolenBasePercentage" : ".789",
          "groundIntoDoublePlay" : 2,
          "numberOfPitches" : 2494,
          "plateAppearances" : 702,
          "totalBases" : 320,
          "rbi" : 86,
          "leftOnBase" : 209,
          "sacBunts" : 0,
          "sacFlies" : 4,
          "babip" : ".325",
          "groundOutsToAirouts" : "0.77",
          "atBatsPerHomeRun" : "26.67"
        },
        "team" : {
          "id" : 144,
          "name" : "Atlanta Braves",
          "link" : "/api/v1/teams/144"
        },
        "league" : {
          "id" : 104,
          "name" : "National League",
          "link" : "/api/v1/league/104"
        },
        "gameType" : "R"
      } ]
    } ],
    "mlbDebutDate" : "2017-08-01",
    "batSide" : {
      "code" : "S",
      "description" : "Switch"
    },
    "pitchHand" : {
      "code" : "R",
      "description" : "Right"
    },
    "nameFirstLast" : "Ozzie Albies",
    "nameSlug" : "ozzie-albies-645277",
    "firstLastName" : "Ozzie Albies",
    "lastFirstName" : "Albies, Ozzie",
    "lastInitName" : "Albies, O",
    "initLastName" : "O Albies",
    "fullFMLName" : "Ozhaino Jurdy Jiandro Albies",
    "fullLFMName" : "Albies, Ozhaino Jurdy Jiandro",
    "strikeZoneTop" : 3.26,
    "strikeZoneBottom" : 1.55
  }, {
    "id" : 593428,
    "fullName" : "Xander Bogaerts",
    "link" : "/api/v1/people/593428",
    "firstName" : "Xander",
    "lastName" : "Bogaerts",
    "primaryNumber" : "2",
    "birthDate" : "1992-10-01",
    "currentAge" : 27,
    "birthCity" : "Oranjestad",
    "birthCountry" : "Aruba",
    "height" : "6' 1\"",
    "weight" : 210,
    "active" : true,
    "primaryPosition" : {
      "code" : "6",
      "name" : "Shortstop",
      "type" : "Infielder",
      "abbreviation" : "SS"
    },
    "useName" : "Xander",
    "middleName" : "Jan",
    "boxscoreName" : "Bogaerts",
    "nickName" : "X-Man",
    "gender" : "M",
    "isPlayer" : true,
    "isVerified" : true,
    "pronunciation" : "BOH-gahrts",
    "stats" : [ {
      "type" : {
        "displayName" : "season"
      },
      "group" : {
        "displayName" : "hitting"
      },
      "exemptions" : [ ],
      "splits" : [ {
        "season" : "2019",
        "stat" : {
          "gamesPlayed" : 155,
          "groundOuts" : 151,
          "airOuts" : 157,
          "runs" : 110,
          "doubles" : 52,
          "triples" : 0,
          "homeRuns" : 33,
          "strikeOuts" : 122,
          "baseOnBalls" : 76,
          "intentionalWalks" : 2,
          "hits" : 190,
          "hitByPitch" : 2,
          "avg" : ".309",
          "atBats" : 614,
          "obp" : ".384",
          "slg" : ".555",
          "ops" : ".939",
          "caughtStealing" : 2,
          "stolenBases" : 4,
          "stolenBasePercentage" : ".667",
          "groundIntoDoublePlay" : 11,
          "numberOfPitches" : 2862,
          "plateAppearances" : 698,
          "totalBases" : 341,
          "rbi" : 117,
          "leftOnBase" : 250,
          "sacBunts" : 0,
          "sacFlies" : 6,
          "babip" : ".338",
          "groundOutsToAirouts" : "0.96",
          "atBatsPerHomeRun" : "18.61"
        },
        "team" : {
          "id" : 111,
          "name" : "Boston Red Sox",
          "link" : "/api/v1/teams/111"
        },
        "league" : {
          "id" : 103,
          "name" : "American League",
          "link" : "/api/v1/league/103"
        },
        "gameType" : "R"
      } ]
    } ],
    "mlbDebutDate" : "2013-08-20",
    "batSide" : {
      "code" : "R",
      "description" : "Right"
    },
    "pitchHand" : {
      "code" : "R",
      "description" : "Right"
    },
    "nameFirstLast" : "Xander Bogaerts",
    "nameSlug" : "xander-bogaerts-593428",
    "firstLastName" : "Xander Bogaerts",
    "lastFirstName" : "Bogaerts, Xander",
    "lastInitName" : "Bogaerts, X",
    "initLastName" : "X Bogaerts",
    "fullFMLName" : "Xander Jan Bogaerts",
    "fullLFMName" : "Bogaerts, Xander Jan",
    "strikeZoneTop" : 3.51,
    "strikeZoneBottom" : 1.62
  }, {
    "id" : 544369,
    "fullName" : "Didi Gregorius",
    "link" : "/api/v1/people/544369",
    "firstName" : "Mariekson",
    "lastName" : "Gregorius",
    "primaryNumber" : "18",
    "birthDate" : "1990-02-18",
    "currentAge" : 30,
    "birthCity" : "Amsterdam",
    "birthCountry" : "Netherlands",
    "height" : "6' 3\"",
    "weight" : 205,
    "active" : true,
    "primaryPosition" : {
      "code" : "6",
      "name" : "Shortstop",
      "type" : "Infielder",
      "abbreviation" : "SS"
    },
    "useName" : "Didi",
    "middleName" : "Julius",
    "boxscoreName" : "Gregorius",
    "nickName" : "Sir MJG",
    "gender" : "M",
    "isPlayer" : true,
    "isVerified" : true,
    "pronunciation" : "dee-dee GREG-or-ee-us",
    "stats" : [ {
      "type" : {
        "displayName" : "season"
      },
      "group" : {
        "displayName" : "hitting"
      },
      "exemptions" : [ ],
      "splits" : [ {
        "season" : "2019",
        "stat" : {
          "gamesPlayed" : 82,
          "groundOuts" : 79,
          "airOuts" : 117,
          "runs" : 47,
          "doubles" : 14,
          "triples" : 2,
          "homeRuns" : 16,
          "strikeOuts" : 53,
          "baseOnBalls" : 17,
          "intentionalWalks" : 1,
          "hits" : 77,
          "hitByPitch" : 1,
          "avg" : ".238",
          "atBats" : 324,
          "obp" : ".276",
          "slg" : ".441",
          "ops" : ".718",
          "caughtStealing" : 1,
          "stolenBases" : 2,
          "stolenBasePercentage" : ".667",
          "groundIntoDoublePlay" : 5,
          "numberOfPitches" : 1378,
          "plateAppearances" : 344,
          "totalBases" : 143,
          "rbi" : 61,
          "leftOnBase" : 134,
          "sacBunts" : 0,
          "sacFlies" : 2,
          "babip" : ".237",
          "groundOutsToAirouts" : "0.68",
          "atBatsPerHomeRun" : "20.25"
        },
        "team" : {
          "id" : 147,
          "name" : "New York Yankees",
          "link" : "/api/v1/teams/147"
        },
        "league" : {
          "id" : 103,
          "name" : "American League",
          "link" : "/api/v1/league/103"
        },
        "gameType" : "R"
      } ]
    } ],
    "mlbDebutDate" : "2012-09-05",
    "batSide" : {
      "code" : "L",
      "description" : "Left"
    },
    "pitchHand" : {
      "code" : "R",
      "description" : "Right"
    },
    "nameFirstLast" : "Didi Gregorius",
    "nameSlug" : "didi-gregorius-544369",
    "firstLastName" : "Didi Gregorius",
    "lastFirstName" : "Gregorius, Didi",
    "lastInitName" : "Gregorius, D",
    "initLastName" : "D Gregorius",
    "fullFMLName" : "Mariekson Julius Gregorius",
    "fullLFMName" : "Gregorius, Mariekson Julius",
    "strikeZoneTop" : 3.34,
    "strikeZoneBottom" : 1.65
  }, {
    "id" : 445276,
    "fullName" : "Kenley Jansen",
    "link" : "/api/v1/people/445276",
    "firstName" : "Kenley",
    "lastName" : "Jansen",
    "primaryNumber" : "74",
    "birthDate" : "1987-09-30",
    "currentAge" : 32,
    "birthCity" : "Willemstad",
    "birthCountry" : "Curacao",
    "height" : "6' 5\"",
    "weight" : 265,
    "active" : true,
    "primaryPosition" : {
      "code" : "1",
      "name" : "Pitcher",
      "type" : "Pitcher",
      "abbreviation" : "P"
    },
    "useName" : "Kenley",
    "middleName" : "Geronimo",
    "boxscoreName" : "Jansen, K",
    "nickName" : "Kenleyfornia",
    "gender" : "M",
    "isPlayer" : true,
    "isVerified" : true,
    "pronunciation" : "KEHN-lee JAN-sin",
    "stats" : [ {
      "type" : {
        "displayName" : "season"
      },
      "group" : {
        "displayName" : "pitching"
      },
      "exemptions" : [ ],
      "splits" : [ {
        "season" : "2019",
        "stat" : {
          "gamesPlayed" : 62,
          "gamesStarted" : 0,
          "groundOuts" : 44,
          "airOuts" : 68,
          "runs" : 28,
          "doubles" : 12,
          "triples" : 1,
          "homeRuns" : 9,
          "strikeOuts" : 80,
          "baseOnBalls" : 16,
          "intentionalWalks" : 0,
          "hits" : 51,
          "hitByPitch" : 4,
          "avg" : ".213",
          "atBats" : 240,
          "obp" : ".270",
          "slg" : ".383",
          "ops" : ".653",
          "caughtStealing" : 0,
          "stolenBases" : 13,
          "stolenBasePercentage" : "1.000",
          "groundIntoDoublePlay" : 3,
          "numberOfPitches" : 1068,
          "era" : "3.71",
          "inningsPitched" : "63.0",
          "wins" : 5,
          "losses" : 3,
          "saves" : 33,
          "saveOpportunities" : 41,
          "holds" : 0,
          "earnedRuns" : 26,
          "whip" : "1.06",
          "battersFaced" : 263,
          "gamesPitched" : 62,
          "completeGames" : 0,
          "shutouts" : 0,
          "strikes" : 741,
          "strikePercentage" : "69.4",
          "hitBatsmen" : 4,
          "balks" : 3,
          "wildPitches" : 2,
          "pickoffs" : 0,
          "groundOutsToAirouts" : "0.65",
          "winPercentage" : ".625",
          "pitchesPerInning" : "17.0",
          "gamesFinished" : 51,
          "strikeoutWalkRatio" : "5.00",
          "strikeoutsPer9Inn" : "11.43",
          "walksPer9Inn" : "2.29",
          "hitsPer9Inn" : "7.29",
          "runsScoredPer9" : "2.29",
          "homeRunsPer9" : "1.29",
          "inheritedRunners" : 15,
          "inheritedRunnersScored" : 5,
          "sacBunts" : 0,
          "sacFlies" : 3
        },
        "team" : {
          "id" : 119,
          "name" : "Los Angeles Dodgers",
          "link" : "/api/v1/teams/119"
        },
        "league" : {
          "id" : 104,
          "name" : "National League",
          "link" : "/api/v1/league/104"
        },
        "gameType" : "R"
      } ]
    } ],
    "mlbDebutDate" : "2010-07-24",
    "batSide" : {
      "code" : "S",
      "description" : "Switch"
    },
    "pitchHand" : {
      "code" : "R",
      "description" : "Right"
    },
    "nameFirstLast" : "Kenley Jansen",
    "nameSlug" : "kenley-jansen-445276",
    "firstLastName" : "Kenley Jansen",
    "lastFirstName" : "Jansen, Kenley",
    "lastInitName" : "Jansen, K",
    "initLastName" : "K Jansen",
    "fullFMLName" : "Kenley Geronimo Jansen",
    "fullLFMName" : "Jansen, Kenley Geronimo",
    "strikeZoneTop" : 3.575,
    "strikeZoneBottom" : 1.681
  }, {
    "id" : 595777,
    "fullName" : "Jurickson Profar",
    "link" : "/api/v1/people/595777",
    "firstName" : "Jurickson",
    "lastName" : "Profar",
    "primaryNumber" : "10",
    "birthDate" : "1993-02-20",
    "currentAge" : 27,
    "birthCity" : "Willemstad",
    "birthCountry" : "Curacao",
    "height" : "6' 0\"",
    "weight" : 190,
    "active" : true,
    "primaryPosition" : {
      "code" : "4",
      "name" : "Second Base",
      "type" : "Infielder",
      "abbreviation" : "2B"
    },
    "useName" : "Jurickson",
    "middleName" : "Barthelomeus",
    "boxscoreName" : "Profar",
    "nickName" : "El Patron",
    "gender" : "M",
    "isPlayer" : true,
    "isVerified" : true,
    "pronunciation" : "JER-ik-suhn PROH-fahr",
    "stats" : [ {
      "type" : {
        "displayName" : "season"
      },
      "group" : {
        "displayName" : "hitting"
      },
      "exemptions" : [ ],
      "splits" : [ {
        "season" : "2019",
        "stat" : {
          "gamesPlayed" : 139,
          "groundOuts" : 138,
          "airOuts" : 149,
          "runs" : 65,
          "doubles" : 24,
          "triples" : 2,
          "homeRuns" : 20,
          "strikeOuts" : 75,
          "baseOnBalls" : 48,
          "intentionalWalks" : 2,
          "hits" : 100,
          "hitByPitch" : 8,
          "avg" : ".218",
          "atBats" : 459,
          "obp" : ".301",
          "slg" : ".410",
          "ops" : ".711",
          "caughtStealing" : 1,
          "stolenBases" : 9,
          "stolenBasePercentage" : ".900",
          "groundIntoDoublePlay" : 12,
          "numberOfPitches" : 2061,
          "plateAppearances" : 518,
          "totalBases" : 188,
          "rbi" : 67,
          "leftOnBase" : 229,
          "sacBunts" : 0,
          "sacFlies" : 3,
          "babip" : ".218",
          "groundOutsToAirouts" : "0.93",
          "atBatsPerHomeRun" : "22.95"
        },
        "team" : {
          "id" : 133,
          "name" : "Oakland Athletics",
          "link" : "/api/v1/teams/133"
        },
        "league" : {
          "id" : 103,
          "name" : "American League",
          "link" : "/api/v1/league/103"
        },
        "gameType" : "R"
      } ]
    } ],
    "mlbDebutDate" : "2012-09-02",
    "batSide" : {
      "code" : "S",
      "description" : "Switch"
    },
    "pitchHand" : {
      "code" : "R",
      "description" : "Right"
    },
    "nameFirstLast" : "Jurickson Profar",
    "nameSlug" : "jurickson-profar-595777",
    "firstLastName" : "Jurickson Profar",
    "lastFirstName" : "Profar, Jurickson",
    "lastInitName" : "Profar, J",
    "initLastName" : "J Profar",
    "fullFMLName" : "Jurickson Barthelomeus Profar",
    "fullLFMName" : "Profar, Jurickson Barthelomeus",
    "strikeZoneTop" : 3.25,
    "strikeZoneBottom" : 1.57
  }, {
    "id" : 570731,
    "fullName" : "Jonathan Schoop",
    "link" : "/api/v1/people/570731",
    "firstName" : "Jonathan",
    "lastName" : "Schoop",
    "primaryNumber" : "8",
    "birthDate" : "1991-10-16",
    "currentAge" : 28,
    "birthCity" : "Willemstad",
    "birthCountry" : "Curacao",
    "height" : "6' 1\"",
    "weight" : 225,
    "active" : true,
    "primaryPosition" : {
      "code" : "4",
      "name" : "Second Base",
      "type" : "Infielder",
      "abbreviation" : "2B"
    },
    "useName" : "Jonathan",
    "middleName" : "Rufino Jezus",
    "boxscoreName" : "Schoop",
    "nickName" : "Mamba",
    "gender" : "M",
    "isPlayer" : true,
    "isVerified" : true,
    "pronunciation" : "Scope",
    "stats" : [ {
      "type" : {
        "displayName" : "season"
      },
      "group" : {
        "displayName" : "hitting"
      },
      "exemptions" : [ ],
      "splits" : [ {
        "season" : "2019",
        "stat" : {
          "gamesPlayed" : 121,
          "groundOuts" : 107,
          "airOuts" : 100,
          "runs" : 61,
          "doubles" : 23,
          "triples" : 1,
          "homeRuns" : 23,
          "strikeOuts" : 116,
          "baseOnBalls" : 20,
          "intentionalWalks" : 1,
          "hits" : 111,
          "hitByPitch" : 10,
          "avg" : ".256",
          "atBats" : 433,
          "obp" : ".304",
          "slg" : ".473",
          "ops" : ".777",
          "caughtStealing" : 1,
          "stolenBases" : 1,
          "stolenBasePercentage" : ".500",
          "groundIntoDoublePlay" : 13,
          "numberOfPitches" : 1681,
          "plateAppearances" : 464,
          "totalBases" : 205,
          "rbi" : 59,
          "leftOnBase" : 220,
          "sacBunts" : 0,
          "sacFlies" : 1,
          "babip" : ".298",
          "groundOutsToAirouts" : "1.07",
          "atBatsPerHomeRun" : "18.83"
        },
        "team" : {
          "id" : 142,
          "name" : "Minnesota Twins",
          "link" : "/api/v1/teams/142"
        },
        "league" : {
          "id" : 103,
          "name" : "American League",
          "link" : "/api/v1/league/103"
        },
        "gameType" : "R"
      } ]
    } ],
    "mlbDebutDate" : "2013-09-25",
    "batSide" : {
      "code" : "R",
      "description" : "Right"
    },
    "pitchHand" : {
      "code" : "R",
      "description" : "Right"
    },
    "nameFirstLast" : "Jonathan Schoop",
    "nameSlug" : "jonathan-schoop-570731",
    "firstLastName" : "Jonathan Schoop",
    "lastFirstName" : "Schoop, Jonathan",
    "lastInitName" : "Schoop, J",
    "initLastName" : "J Schoop",
    "fullFMLName" : "Jonathan Rufino Jezus Schoop",
    "fullLFMName" : "Schoop, Jonathan Rufino Jezus",
    "strikeZoneTop" : 3.54,
    "strikeZoneBottom" : 1.69
  }, {
    "id" : 592743,
    "fullName" : "Andrelton Simmons",
    "link" : "/api/v1/people/592743",
    "firstName" : "Andrelton",
    "lastName" : "Simmons",
    "primaryNumber" : "2",
    "birthDate" : "1989-09-04",
    "currentAge" : 30,
    "birthCity" : "Mundo-Novo",
    "birthCountry" : "Curacao",
    "height" : "6' 2\"",
    "weight" : 195,
    "active" : true,
    "primaryPosition" : {
      "code" : "6",
      "name" : "Shortstop",
      "type" : "Infielder",
      "abbreviation" : "SS"
    },
    "useName" : "Andrelton",
    "middleName" : "A.",
    "boxscoreName" : "Simmons",
    "nickName" : "Simba",
    "gender" : "M",
    "isPlayer" : true,
    "isVerified" : true,
    "draftYear" : 2010,
    "pronunciation" : "ANN-drull-ton",
    "stats" : [ {
      "type" : {
        "displayName" : "season"
      },
      "group" : {
        "displayName" : "hitting"
      },
      "exemptions" : [ ],
      "splits" : [ {
        "season" : "2019",
        "stat" : {
          "gamesPlayed" : 103,
          "groundOuts" : 142,
          "airOuts" : 114,
          "runs" : 47,
          "doubles" : 19,
          "triples" : 0,
          "homeRuns" : 7,
          "strikeOuts" : 37,
          "baseOnBalls" : 24,
          "intentionalWalks" : 1,
          "hits" : 105,
          "hitByPitch" : 2,
          "avg" : ".264",
          "atBats" : 398,
          "obp" : ".309",
          "slg" : ".364",
          "ops" : ".673",
          "caughtStealing" : 2,
          "stolenBases" : 10,
          "stolenBasePercentage" : ".833",
          "groundIntoDoublePlay" : 21,
          "numberOfPitches" : 1389,
          "plateAppearances" : 424,
          "totalBases" : 145,
          "rbi" : 40,
          "leftOnBase" : 171,
          "sacBunts" : 0,
          "sacFlies" : 0,
          "babip" : ".277",
          "groundOutsToAirouts" : "1.25",
          "atBatsPerHomeRun" : "56.86"
        },
        "team" : {
          "id" : 108,
          "name" : "Los Angeles Angels",
          "link" : "/api/v1/teams/108"
        },
        "league" : {
          "id" : 103,
          "name" : "American League",
          "link" : "/api/v1/league/103"
        },
        "gameType" : "R"
      } ]
    } ],
    "mlbDebutDate" : "2012-06-02",
    "batSide" : {
      "code" : "R",
      "description" : "Right"
    },
    "pitchHand" : {
      "code" : "R",
      "description" : "Right"
    },
    "nameFirstLast" : "Andrelton Simmons",
    "nameSlug" : "andrelton-simmons-592743",
    "firstLastName" : "Andrelton Simmons",
    "lastFirstName" : "Simmons, Andrelton",
    "lastInitName" : "Simmons, A",
    "initLastName" : "A Simmons",
    "fullFMLName" : "Andrelton A. Simmons",
    "fullLFMName" : "Simmons, Andrelton A.",
    "strikeZoneTop" : 3.41,
    "strikeZoneBottom" : 1.64
  }, {
    "id" : 467008,
    "fullName" : "Pedro Strop",
    "link" : "/api/v1/people/467008",
    "firstName" : "Pedro",
    "lastName" : "Strop",
    "primaryNumber" : "46",
    "birthDate" : "1985-06-13",
    "currentAge" : 34,
    "birthCity" : "San Cristobal",
    "birthCountry" : "Dominican Republic",
    "height" : "6' 1\"",
    "weight" : 220,
    "active" : true,
    "primaryPosition" : {
      "code" : "1",
      "name" : "Pitcher",
      "type" : "Pitcher",
      "abbreviation" : "P"
    },
    "useName" : "Pedro",
    "middleName" : "Angel",
    "boxscoreName" : "Strop",
    "nickName" : "Stropy",
    "gender" : "M",
    "isPlayer" : true,
    "isVerified" : true,
    "pronunciation" : "Strope",
    "stats" : [ {
      "type" : {
        "displayName" : "season"
      },
      "group" : {
        "displayName" : "pitching"
      },
      "exemptions" : [ ],
      "splits" : [ {
        "season" : "2019",
        "stat" : {
          "gamesPlayed" : 50,
          "gamesStarted" : 0,
          "groundOuts" : 43,
          "airOuts" : 28,
          "runs" : 24,
          "doubles" : 9,
          "triples" : 1,
          "homeRuns" : 6,
          "strikeOuts" : 49,
          "baseOnBalls" : 20,
          "intentionalWalks" : 1,
          "hits" : 33,
          "hitByPitch" : 5,
          "avg" : ".217",
          "atBats" : 152,
          "obp" : ".326",
          "slg" : ".408",
          "ops" : ".734",
          "caughtStealing" : 0,
          "stolenBases" : 0,
          "stolenBasePercentage" : ".---",
          "groundIntoDoublePlay" : 4,
          "numberOfPitches" : 737,
          "era" : "4.97",
          "inningsPitched" : "41.2",
          "wins" : 2,
          "losses" : 5,
          "saves" : 10,
          "saveOpportunities" : 16,
          "holds" : 6,
          "earnedRuns" : 23,
          "whip" : "1.27",
          "battersFaced" : 178,
          "gamesPitched" : 50,
          "completeGames" : 0,
          "shutouts" : 0,
          "strikes" : 460,
          "strikePercentage" : "62.4",
          "hitBatsmen" : 5,
          "balks" : 0,
          "wildPitches" : 4,
          "pickoffs" : 1,
          "groundOutsToAirouts" : "1.54",
          "winPercentage" : ".286",
          "pitchesPerInning" : "17.7",
          "gamesFinished" : 27,
          "strikeoutWalkRatio" : "2.45",
          "strikeoutsPer9Inn" : "10.58",
          "walksPer9Inn" : "4.32",
          "hitsPer9Inn" : "7.13",
          "runsScoredPer9" : "2.81",
          "homeRunsPer9" : "1.30",
          "inheritedRunners" : 13,
          "inheritedRunnersScored" : 5,
          "sacBunts" : 0,
          "sacFlies" : 1
        },
        "team" : {
          "id" : 112,
          "name" : "Chicago Cubs",
          "link" : "/api/v1/teams/112"
        },
        "league" : {
          "id" : 104,
          "name" : "National League",
          "link" : "/api/v1/league/104"
        },
        "gameType" : "R"
      } ]
    } ],
    "mlbDebutDate" : "2009-08-28",
    "batSide" : {
      "code" : "R",
      "description" : "Right"
    },
    "pitchHand" : {
      "code" : "R",
      "description" : "Right"
    },
    "nameFirstLast" : "Pedro Strop",
    "nameSlug" : "pedro-strop-467008",
    "firstLastName" : "Pedro Strop",
    "lastFirstName" : "Strop, Pedro",
    "lastInitName" : "Strop, P",
    "initLastName" : "P Strop",
    "fullFMLName" : "Pedro Angel Strop",
    "fullLFMName" : "Strop, Pedro Angel",
    "strikeZoneTop" : 3.411,
    "strikeZoneBottom" : 1.565
  }, {
    "id" : 665989,
    "fullName" : "Shervyen Newton",
    "link" : "/api/v1/people/665989",
    "firstName" : "Shervyen",
    "lastName" : "Newton",
    "primaryNumber" : "85",
    "birthDate" : "1999-04-24",
    "currentAge" : 21,
    "birthCity" : "Tilburg",
    "birthCountry" : "Netherlands",
    "height" : "6' 4\"",
    "weight" : 180,
    "active" : true,
    "primaryPosition" : {
      "code" : "6",
      "name" : "Shortstop",
      "type" : "Infielder",
      "abbreviation" : "SS"
    },
    "useName" : "Shervyen",
    "middleName" : "Lugandro Josua",
    "boxscoreName" : "Newton",
    "gender" : "M",
    "isPlayer" : true,
    "isVerified" : true,
    "batSide" : {
      "code" : "S",
      "description" : "Switch"
    },
    "pitchHand" : {
      "code" : "R",
      "description" : "Right"
    },
    "nameFirstLast" : "Shervyen Newton",
    "nameSlug" : "shervyen-newton-665989",
    "firstLastName" : "Shervyen Newton",
    "lastFirstName" : "Newton, Shervyen",
    "lastInitName" : "Newton, S",
    "initLastName" : "S Newton",
    "fullFMLName" : "Shervyen Lugandro Josua Newton",
    "fullLFMName" : "Newton, Shervyen Lugandro Josua",
    "strikeZoneTop" : 3.549,
    "strikeZoneBottom" : 1.627
  }, {
    "id" : 678486,
    "fullName" : "Shendrik Apostel",
    "link" : "/api/v1/people/678486",
    "firstName" : "Shendrik",
    "lastName" : "Apostel",
    "birthDate" : "2000-04-24",
    "currentAge" : 20,
    "birthCity" : "Willemstad",
    "birthCountry" : "Curacao",
    "height" : "6' 5\"",
    "weight" : 245,
    "active" : true,
    "primaryPosition" : {
      "code" : "3",
      "name" : "First Base",
      "type" : "Infielder",
      "abbreviation" : "1B"
    },
    "useName" : "Shendrik",
    "middleName" : "Gregorio",
    "boxscoreName" : "Apostel",
    "gender" : "M",
    "isPlayer" : true,
    "isVerified" : false,
    "batSide" : {
      "code" : "R",
      "description" : "Right"
    },
    "pitchHand" : {
      "code" : "R",
      "description" : "Right"
    },
    "nameFirstLast" : "Shendrik Apostel",
    "nameSlug" : "shendrik-apostel-678486",
    "firstLastName" : "Shendrik Apostel",
    "lastFirstName" : "Apostel, Shendrik",
    "lastInitName" : "Apostel, S",
    "initLastName" : "S Apostel",
    "fullFMLName" : "Shendrik Gregorio Apostel",
    "fullLFMName" : "Apostel, Shendrik Gregorio",
    "strikeZoneTop" : 3.575,
    "strikeZoneBottom" : 1.681
  } ]
}